version = 5.3.1
archive_dir = /etc/letsencrypt/archive/quickpick.coach
cert = /etc/letsencrypt/live/quickpick.coach/cert.pem
privkey = /etc/letsencrypt/live/quickpick.coach/privkey.pem
chain = /etc/letsencrypt/live/quickpick.coach/chain.pem
fullchain = /etc/letsencrypt/live/quickpick.coach/fullchain.pem
[renewalparams]
account = 32dd6ab300065d2341f3dd0c83d82967
authenticator = webroot
webroot_path = /var/www/certbot,
server = https://acme-v02.api.letsencrypt.org/directory
key_type = ecdsa
[[webroot_map]]
